allow customizing the worker names and do not override defaults
dask/dask-mpi pull request #52
Opened 2020-10-14 06:11 UTC by jglaser

In order to support using `dask-mpi` as a backend for multiple workers per job in `dask-gateway`, I am introducing the capability to set a custom name, to which the rank is appended. This change is needed for keeping track of workers in `dask-gateway` (PR to be submitted). In addition, I am reverting some of the default overrides for the CLI options, as those for example set the TCP protocol and a scheduler-file, whereas the `dask-gateway` use case requires being able to specify a scheduler address from the command line.

2020-11-25 19:15 UTC, kmpaul requested changes
@jglaser:  So, this PR does more than it says in the title.  It removes some default values for many parameters (causing failures in the CI), in addition to allowing the user to specify base worker names.  Maybe these two changes could be split into separate PRs?  I'm positive the worker name changes can be done very quickly.  The other changes will require some debugging, I think.

2021-01-26 22:42 UTC, kmpaul commented
@jglaser:  I suspect that the

2021-08-30 18:17 UTC, kmpaul requested changes
These suggestions should fix your linting errors.

2021-08-30 18:17 UTC, kmpaul commented on dask_mpi/cli.py
> +
```suggestion
@click.argument("scheduler_address", type=str, required=False)
```

2021-08-30 18:17 UTC, kmpaul commented on dask_mpi/cli.py
> +@click.option("--nthreads", type=int, default=None, help="Number of threads per worker.")
```suggestion
@click.option(
    "--nthreads", type=int, default=None, help="Number of threads per worker."
)
```

2021-08-30 18:17 UTC, kmpaul commented on dask_mpi/cli.py
> +    name
```suggestion
    name,
```

2021-08-30 18:42 UTC, kmpaul commented
@jglaser:  Hey!  I got this to pass.  Do you want me to merge this in now?

2021-08-30 18:42 UTC, kmpaul approved these changes
Got it to pass!

2021-08-30 18:45 UTC, jglaser commented
Thanks for fixing it , @kmpaul .... and sorry for abandoning the issue. Please feel free to merge.

2021-08-30 19:19 UTC, kmpaul commented
Now worries.  And thanks, @jglaser!

2021-08-30 19:19 UTC, merged